# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 17:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('rut', models.IntegerField(validators=[django.core.validators.MaxValueValidator], verbose_name='RUT')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('MVD', 'Montevideo'), ('ART', 'Artigas'), ('CAN', 'Canelones'), ('CER', 'Cerro Largo'), ('COL', 'Colonia'), ('DUR', 'Durazno'), ('FLO', 'Flores'), ('FLA', 'Florida'), ('LAV', 'Lavalleja'), ('MAL', 'Maldonado'), ('PAY', 'Paysandu'), ('RNG', 'Rio Negro'), ('RIV', 'Rivera'), ('RCH', 'Rocha'), ('SAL', 'Salto'), ('SAJ', 'San Jose'), ('SOR', 'Soriano'), ('TAC', 'Tacuarembo'), ('TYT', 'Treinta y Tres')], default='MVD', max_length=3)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('logo', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('state', models.CharField(choices=[('MVD', 'Montevideo'), ('ART', 'Artigas'), ('CAN', 'Canelones'), ('CER', 'Cerro Largo'), ('COL', 'Colonia'), ('DUR', 'Durazno'), ('FLO', 'Flores'), ('FLA', 'Florida'), ('LAV', 'Lavalleja'), ('MAL', 'Maldonado'), ('PAY', 'Paysandu'), ('RNG', 'Rio Negro'), ('RIV', 'Rivera'), ('RCH', 'Rocha'), ('SAL', 'Salto'), ('SAJ', 'San Jose'), ('SOR', 'Soriano'), ('TAC', 'Tacuarembo'), ('TYT', 'Treinta y Tres')], default='MVD', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
    ]
