# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 15:15
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160219_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='country',
            field=django_countries.fields.CountryField(default='UY', max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='UY', max_length=2),
        ),
    ]
